### ISSUE TITLE
Frame SVG's open as the wrong size

### ISSUE THREAD

**Issue by Papester** [masto/LED-Marquee#1]
I have downloaded the three Interlocking Frame files and when I open them up in lightburn their size is mush smaller than the actual LED matrix. Could you tell me the dimensions of the actual frames or provide the correct size in the file section.

**Comment by masto** [comment]
Sorry, I just saw this. The frames are 96mm tall, so if you can scale it proportionally to that height it should work.

But think I see the problem with my SVG exports. I am installing a LightBurn trial now and I will update the files in the repository as soon as I've confirmed the fix.

**Comment by Papester** [comment]
> Sorry, I just saw this. The frames are 96mm tall, so if you can scale it proportionally to that height it should work.
> 
> But think I see the problem with my SVG exports. I am installing a LightBurn trial now and I will update the files in the repository as soon as I've confirmed the fix.

Thanks I figured it out and had resized them, my final height was about 96.3mm, very close to you recommended size.

Thanks for your reply.

**Comment by masto** [comment]
I think the latest files should work correctly. Sorry for taking so long to get back to you.

**Comment by masto** [comment]
Also, for the record and hopefully to avoid confusing anyone else: the files are indeed slightly larger than 96mm. I designed them in Fusion 360 and the conversion process applies a kerf correction.
